spring:
  data:
    mongodb:
      username: dimas
      password: dimas
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: 127.0.0:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      Properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.dimas.notification.kafka.order.OrderConfirmation,paymentConfirmation:com.dimas.notification.kafka.payment.PaymentConfirmation;
  mail:
    host: localhost
    port: 1025
    username: dimas
    password: dimas
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 50000
        timeout: 30000
        writetimeout: 50000
server:
  port: 8020