spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: dimas
    password: dimas
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      bootstrap-servers:  127.0.0:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.dimas.payment.kafka.PaymentNotificationRequest;
server:
  port: 8085
